repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff lint
        entry: ruff check --fix sqlamodels
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff-format
        name: ruff format
        entry: ruff format sqlamodels
        language: system
        types: [python]
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy --python-executable=.venv/bin/python3 sqlamodels
        language: system
        types: [python]
        pass_filenames: false
